In [64]:
import numpy as np
import pandas as pd

In [65]:
tips = pd.read_csv("/Users/tishikaagarwal/Desktop/Machine Learning/Data/tip.csv")

In [66]:
tips.groupby("day")["total_bill"].size()

day
Fri     19
Sat     87
Sun     76
Thur    62
Name: total_bill, dtype: int64

In [67]:
tips.groupby("day")["total_bill"].mean()

day
Fri     17.151579
Sat     20.441379
Sun     21.410000
Thur    17.682742
Name: total_bill, dtype: float64

In [68]:
tips.groupby("day")["tip"].mean()

day
Fri     2.734737
Sat     2.993103
Sun     3.255132
Thur    2.771452
Name: tip, dtype: float64

In [69]:
tips.groupby("day").agg(
    Bill_count = ("total_bill" , 'size'),
    avg_bill = ("total_bill" , 'mean'),
    avg_tip = ("tip" , 'mean')
)

      Bill_count   avg_bill   avg_tip
day
Fri           19  17.151579  2.734737
Sat           87  20.441379  2.993103
Sun           76  21.410000  3.255132
Thur          62  17.682742  2.771452

In [70]:
tips.groupby("time").agg(
    Bill_count = ("total_bill" , 'size'),
    avg_bill = ("total_bill" , 'mean'),
    avg_party = ("size" , 'mean')
)

        Bill_count   avg_bill  avg_party
time
Dinner         176  20.797159   2.630682
Lunch           68  17.168676   2.411765

In [71]:
summary = tips.groupby("day").agg(
    Bill_count = ("total_bill" , 'size'),
    avg_bill = ("total_bill" , 'mean'),
    avg_party = ("size" , 'mean')
).round(2)
summary

      Bill_count  avg_bill  avg_party
day
Fri           19     17.15       2.11
Sat           87     20.44       2.52
Sun           76     21.41       2.84
Thur          62     17.68       2.45

In [75]:
summary[summary["Bill_count"] == 'Sun']

Empty DataFrame
Columns: [Bill_count, avg_bill, avg_party]
Index: []

In [ ]:
print(summary.columns.tolist())
print(summary.index.tolist())

['Bill_count', 'avg_bill', 'avg_party']
['Fri', 'Sat', 'Sun', 'Thur']

In [ ]:
# print(summary.reset_index())
flat = summary.reset_index()
print(flat.columns.tolist())
flat.head()

['day', 'Bill_count', 'avg_bill', 'avg_party']

    day  Bill_count  avg_bill  avg_party
0   Fri          19     17.15       2.11
1   Sat          87     20.44       2.52
2   Sun          76     21.41       2.84
3  Thur          62     17.68       2.45

In [ ]:
summary

      Bill_count  avg_bill  avg_party
day
Fri           19     17.15       2.11
Sat           87     20.44       2.52
Sun           76     21.41       2.84
Thur          62     17.68       2.45

In [ ]:
summary.to_csv("Report.csv")
flat = pd.read_csv("Report.csv")
flat.head()

    day  Bill_count  avg_bill  avg_party
0   Fri          19     17.15       2.11
1   Sat          87     20.44       2.52
2   Sun          76     21.41       2.84
3  Thur          62     17.68       2.45

In [ ]:
summm = tips.groupby("smoker").agg(
    num_bill = ("total_bill" , 'size'),
    avg_bill = ("total_bill" , 'mean'),
    avg_tip = ("tip" , 'mean')
).round(2)
summm

        num_bill  avg_bill  avg_tip
smoker
No           151     19.19     2.99
Yes           93     20.76     3.01

In [ ]:
summm.reset_index().to_csv("smoker_report.csv", index=False)
report = pd.read_csv("smoker_report.csv")
report.head()

  smoker  num_bill  avg_bill  avg_tip
0     No       151     19.19     2.99
1    Yes        93     20.76     3.01

In [ ]:
tips.groupby("day")["tip"].max()

day
Fri      4.73
Sat     10.00
Sun      6.50
Thur     6.70
Name: tip, dtype: float64

In [ ]:
tips.groupby("day")["tip"].idxmax()

day
Fri      95
Sat     170
Sun     183
Thur    141
Name: tip, dtype: int64

In [ ]:
print(tips.loc[170])

total_bill     50.81
tip             10.0
sex             Male
smoker           Yes
day              Sat
time          Dinner
size               3
Name: 170, dtype: object

In [ ]:
bookings = pd.read_csv("/Users/tishikaagarwal/Desktop/Machine Learning/Data/bookings.csv")
bookings

    booking_id        customer  day    time  party_size
0          101     ravi sharma  Sat  Dinner         4.0
1          102      PRIYA IYER  Sat  Dinner         2.0
2          103    Ravi Sharma   Sun   Lunch         NaN
3          104      amit kumar  Sun  Dinner         6.0
4          105     priya  iyer  Fri  Dinner         NaN
5          106     RAVI SHARMA  Sat   Lunch         3.0
6          107       sana khan  Sat   Lunch         NaN
7          108      Amit Kumar  Sat  Dinner         5.0
8          109      vikram rao  Sun  Dinner         2.0
9          110      Sana  Khan  Fri  Dinner         4.0
10         111      priya iyer  Sat   Lunch         NaN
11         112      VIKRAM RAO  Sun   Lunch         3.0

In [ ]:
bookings["customer"].nunique()

12

In [ ]:
print(bookings["customer"].str.lower().str.strip())
# print(bookings["customer"].str.strip())

0     ravi sharma
1      priya iyer
2     ravi sharma
3      amit kumar
4     priya  iyer
5     ravi sharma
6       sana khan
7      amit kumar
8      vikram rao
9      sana  khan
10     priya iyer
11     vikram rao
Name: customer, dtype: str

In [ ]:
bookings["customer"] = bookings["customer"].str.lower().str.strip()\
                       .str.split().str.join(" ")

5

In [ ]:
print(bookings["customer"].nunique())
print(bookings["customer"].unique())
print(bookings["customer"].unique().tolist())

5
['ravi sharma' 'priya iyer' 'amit kumar' 'sana khan' 'vikram rao']
['ravi sharma', 'priya iyer', 'amit kumar', 'sana khan', 'vikram rao']