In [19]:
import pandas as pd
import numpy as np

df = pd.read_csv('tip.csv')          # keep the file next to this notebook
# df = pd.read_csv('/Users/shailesh/Desktop/vedam_Sem3_ml/Data/tip.csv')

df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [20]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [21]:
# selecting many columns
x=df['day']
print(type(x))
print(x.shape)
y=df[['day']]
print(type(y))
print(y.shape)
y=df[['total_bill','day','tip']]
print(y.head())

<class 'pandas.Series'>
(244,)
<class 'pandas.DataFrame'>
(244, 1)
   total_bill  day   tip
0       16.99  Sun  1.01
1       10.34  Sun  1.66
2       21.01  Sun  3.50
3       23.68  Sun  3.31
4       24.59  Sun  3.61

In [22]:
# making a new column
#Add a column called `bill_per_person` — the bill divided by the number of people
df['country']="India"
df['bill_per_person']=round(df['total_bill']/df['size'],2)

df.head()

   total_bill   tip     sex smoker  day    time  size country  bill_per_person
0       16.99  1.01  Female     No  Sun  Dinner     2   India             8.49
1       10.34  1.66    Male     No  Sun  Dinner     3   India             3.45
2       21.01  3.50    Male     No  Sun  Dinner     3   India             7.00
3       23.68  3.31    Male     No  Sun  Dinner     2   India            11.84
4       24.59  3.61  Female     No  Sun  Dinner     4   India             6.15

🧩 Try these
1.1 Add a column called total_paid — the bill plus the tip. Write the full line.

df['total_paid'] = ____

In [23]:
# 1.1  — total_paid = bill + tip
df['total_paid']=df['tip']+df['total_bill']
df.head()

,total_bill,tip,sex,smoker,day,time,size,country,bill_per_person,total_paid
0,16.99,1.01,Female,No,Sun,Dinner,2,India,8.49,18.00
1,10.34,1.66,Male,No,Sun,Dinner,3,India,3.45,12.00
2,21.01,3.50,Male,No,Sun,Dinner,3,India,7.00,24.51
3,23.68,3.31,Male,No,Sun,Dinner,2,India,11.84,26.99
4,24.59,3.61,Female,No,Sun,Dinner,4,India,6.15,28.20

1.2 Run both of these and print type() of each. One is a single column, one is a table that happens to have one column. Which is which?

df['tip']
df[['tip']]

In [24]:
# 1.2

🔧 Break my code
Both lines are wrong. Find the mistake without running them.

df.shape()
df['total_bill', 'tip']
💬 Type the mistake in chat — but press Enter only when I say go.

In [25]:
# what is wrong?
df.head(6)

,total_bill,tip,sex,smoker,day,time,size,country,bill_per_person,total_paid
0,16.99,1.01,Female,No,Sun,Dinner,2,India,8.49,18.00
1,10.34,1.66,Male,No,Sun,Dinner,3,India,3.45,12.00
2,21.01,3.50,Male,No,Sun,Dinner,3,India,7.00,24.51
3,23.68,3.31,Male,No,Sun,Dinner,2,India,11.84,26.99
4,24.59,3.61,Female,No,Sun,Dinner,4,India,6.15,28.20
5,25.29,4.71,Male,No,Sun,Dinner,4,India,6.32,30.00


2️⃣ iloc — selecting by position
You did this in NumPy. Here we use it to pick rows.

Flow: one row → many rows → rows and columns together

In [26]:
df.head(3)

,total_bill,tip,sex,smoker,day,time,size,country,bill_per_person,total_paid
0,16.99,1.01,Female,No,Sun,Dinner,2,India,8.49,18.00
1,10.34,1.66,Male,No,Sun,Dinner,3,India,3.45,12.00
2,21.01,3.50,Male,No,Sun,Dinner,3,India,7.00,24.51

In [27]:
# iloc — one row, then a slice of rows
# df.iloc[4] for single row
# df.iloc[6:10:2]
# 6,7,8,10
# df.iloc[[6,7,8,10]] # fancy indexing 
df.iloc[(df['bill_per_person']>4).values]

# df.iloc[2,[1,3,5]]

,total_bill,tip,sex,smoker,day,time,size,country,bill_per_person,total_paid
0,16.99,1.01,Female,No,Sun,Dinner,2,India,8.49,18.00
2,21.01,3.50,Male,No,Sun,Dinner,3,India,7.00,24.51
3,23.68,3.31,Male,No,Sun,Dinner,2,India,11.84,26.99
4,24.59,3.61,Female,No,Sun,Dinner,4,India,6.15,28.20
5,25.29,4.71,Male,No,Sun,Dinner,4,India,6.32,30.00
...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3,India,9.68,34.95
240,27.18,2.00,Female,Yes,Sat,Dinner,2,India,13.59,29.18
241,22.67,2.00,Male,Yes,Sat,Dinner,2,India,11.34,24.67
242,17.82,1.75,Male,No,Sat,Dinner,2,India,8.91,19.57
243,18.78,3.00,Female,No,Thur,Dinner,2,India,9.39,21.78

In [ ]:
# iloc — rows and columns by position

In [28]:
df.iloc[3]
print(df.iloc[1:10:2, [1,6]])

print(df.iloc[(df['bill_per_person']>4).values])

    tip  size
1  1.66     3
3  3.31     2
5  4.71     4
7  3.12     4
9  3.23     2
     total_bill   tip     sex smoker   day    time  size country  \
0         16.99  1.01  Female     No   Sun  Dinner     2   India
2         21.01  3.50    Male     No   Sun  Dinner     3   India
3         23.68  3.31    Male     No   Sun  Dinner     2   India
4         24.59  3.61  Female     No   Sun  Dinner     4   India
5         25.29  4.71    Male     No   Sun  Dinner     4   India
..          ...   ...     ...    ...   ...     ...   ...     ...
239       29.03  5.92    Male     No   Sat  Dinner     3   India
240       27.18  2.00  Female    Yes   Sat  Dinner     2   India
241       22.67  2.00    Male    Yes   Sat  Dinner     2   India
242       17.82  1.75    Male     No   Sat  Dinner     2   India
243       18.78  3.00  Female     No  Thur  Dinner     2   India

     bill_per_person  total_paid
0               8.49       18.00
2               7.00       24.51
3              11.84       26.99
4               6.15       28.20
5               6.32       30.00
..               ...         ...
239             9.68       34.95
240            13.59       29.18
241            11.34       24.67
242             8.91       19.57
243             9.39       21.78

[236 rows x 10 columns]

In [29]:
df.head(3)

,total_bill,tip,sex,smoker,day,time,size,country,bill_per_person,total_paid
0,16.99,1.01,Female,No,Sun,Dinner,2,India,8.49,18.00
1,10.34,1.66,Male,No,Sun,Dinner,3,India,3.45,12.00
2,21.01,3.50,Male,No,Sun,Dinner,3,India,7.00,24.51

In [30]:
# loc - one row by its label

df.loc[5:10, 'total_bill':'time']

    total_bill   tip   sex smoker  day    time
5        25.29  4.71  Male     No  Sun  Dinner
6         8.77  2.00  Male     No  Sun  Dinner
7        26.88  3.12  Male     No  Sun  Dinner
8        15.04  1.96  Male     No  Sun  Dinner
9        14.78  3.23  Male     No  Sun  Dinner
10       10.27  1.71  Male     No  Sun  Dinner

🧩 Try these
2.1 Fill the blanks.

df.iloc[____]      # the 6th row
df.iloc[____]      # the last row
df.iloc[____]      # the first 5 rows

In [ ]:
# 2.1  — the 6th row, the last row, the first 5 rows

2.2 Show only day and total_bill. Fill the blank.

print(list(df.columns))     # run this first

df.iloc[10:15, ____]

In [ ]:
df.head()

In [ ]:
# 2.2

df.iloc[10:15,[4,0]]

In [31]:
# 7.1