In [2]:
import numpy as np
import pandas as pd

p = pd.read_csv("/Users/tishikaagarwal/Desktop/Machine Learning/PANDAS/planets.csv")
df = pd.read_csv("/Users/tishikaagarwal/Desktop/Machine Learning/PANDAS/Titanic-Dataset.csv")

In [3]:
df.head(1)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.25,NaN,S

In [4]:
df[df['Age']>65][['Pclass' , 'Name' , "Fare"]]
df[~(df['Embarked'] == "S")].shape[0]

247

In [5]:
df[(df['Age']<10) | (df['Age']>70)].shape[0]
df["Pclass"].value_counts()
df["travel_group"] = "alone"
df.loc[(df["SibSp"] + df["Parch"]>0), "travel_group"] = "With family"

In [6]:
df["travel_group"].value_counts()

travel_group
alone          537
With family    354
Name: count, dtype: int64

In [7]:
p.head()

            method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

In [8]:
# true wherever value is missing

p.isnull().sum()

method              0
number              0
orbital_period     43
mass              522
distance          227
year                0
dtype: int64

In [9]:
# count the blanks in one column

print(p["mass"].isnull().sum())

522

In [10]:
# same information differnent view
p.dropna()

              method  number  orbital_period    mass  distance  year
0    Radial Velocity       1       269.30000   7.100     77.40  2006
1    Radial Velocity       1       874.77400   2.210     56.95  2008
2    Radial Velocity       1       763.00000   2.600     19.84  2011
3    Radial Velocity       1       326.03000  19.400    110.62  2007
4    Radial Velocity       1       516.22000  10.500    119.47  2009
..               ...     ...             ...     ...       ...   ...
640  Radial Velocity       1       111.70000   2.100     14.90  2009
641  Radial Velocity       1         5.05050   1.068     44.46  2013
642  Radial Velocity       1       311.28800   1.940     17.24  1999
649          Transit       1         2.70339   1.470    178.00  2013
784  Radial Velocity       3       580.00000   0.947    135.00  2012

[498 rows x 6 columns]

In [11]:
# drop only where 

p.dropna(subset = ['mass'])
p.dropna(subset = ['mass' , "distance"])

              method  number  orbital_period    mass  distance  year
0    Radial Velocity       1       269.30000   7.100     77.40  2006
1    Radial Velocity       1       874.77400   2.210     56.95  2008
2    Radial Velocity       1       763.00000   2.600     19.84  2011
3    Radial Velocity       1       326.03000  19.400    110.62  2007
4    Radial Velocity       1       516.22000  10.500    119.47  2009
..               ...     ...             ...     ...       ...   ...
640  Radial Velocity       1       111.70000   2.100     14.90  2009
641  Radial Velocity       1         5.05050   1.068     44.46  2013
642  Radial Velocity       1       311.28800   1.940     17.24  1999
649          Transit       1         2.70339   1.470    178.00  2013
784  Radial Velocity       3       580.00000   0.947    135.00  2012

[498 rows x 6 columns]

In [12]:
# drop the damaged columns instead and see which survive
p.dropna(axis=1)

               method  number  year
0     Radial Velocity       1  2006
1     Radial Velocity       1  2008
2     Radial Velocity       1  2011
3     Radial Velocity       1  2007
4     Radial Velocity       1  2009
...               ...     ...   ...
1030          Transit       1  2006
1031          Transit       1  2007
1032          Transit       1  2007
1033          Transit       1  2008
1034          Transit       1  2008

[1035 rows x 3 columns]

In [13]:
# 2.1

df.dropna(subset=["Embarked"])

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,travel_group
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,With family
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,With family
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,alone
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,With family
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,alone
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,alone
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,alone
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,With family
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,alone
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,alone

In [14]:
p["mass"].fillna(0).isnull().sum()
# p["mass"].fillna(p['mass'].mean())
# p["mass"].fillna(p['mass'].median())

np.int64(0)

In [15]:
# how many exact duplicate rows
print(df.duplicated().sum())
print(p.duplicated().sum())

0
4

In [16]:
# show them

p.drop_duplicates()

               method  number  orbital_period   mass  distance  year
0     Radial Velocity       1      269.300000   7.10     77.40  2006
1     Radial Velocity       1      874.774000   2.21     56.95  2008
2     Radial Velocity       1      763.000000   2.60     19.84  2011
3     Radial Velocity       1      326.030000  19.40    110.62  2007
4     Radial Velocity       1      516.220000  10.50    119.47  2009
...               ...     ...             ...    ...       ...   ...
1030          Transit       1        3.941507    NaN    172.00  2006
1031          Transit       1        2.615864    NaN    148.00  2007
1032          Transit       1        3.191524    NaN    174.00  2007
1033          Transit       1        4.125083    NaN    293.00  2008
1034          Transit       1        4.187757    NaN    260.00  2008

[1031 rows x 6 columns]

In [17]:
p.drop_duplicates(subset=["method"])

,method,number,orbital_period,mass,distance,year
0,Radial Velocity,1,269.300000,7.10,77.40,2006
29,Imaging,1,NaN,NaN,45.52,2005
32,Eclipse Timing Variations,1,10220.000000,6.05,NaN,2009
91,Transit,1,1.508956,NaN,NaN,2008
113,Astrometry,1,246.360000,NaN,20.77,2013
680,Transit Timing Variations,2,160.000000,NaN,2119.00,2011
787,Orbital Brightness Modulation,2,0.240104,NaN,1180.00,2011
902,Microlensing,1,NaN,NaN,NaN,2008
941,Pulsar Timing,3,25.262000,NaN,NaN,1992
958,Pulsation Timing Variations,1,1170.000000,NaN,NaN,2007